#!/bin/sh
if type -p ./ccache >/dev/null 2>&1; then
export CCACHE_MAXSIZE=15G
export CCACHE_CPP2=true
export CCACHE_HARDLINK=true
export CCACHE_SLOPPINESS=file_macro,time_macros,include_file_mtime,include_file_ctime,file_stat_matches  
# export CCACHE_LOGFILE='/Users/kaiguo/Documents/work/azclient/proj.ios_mac/CCache.log'
exec ./ccache /usr/bin/clang "$@"
else
exec clang "$@" 
fi